{{- $secretConfig := include "varnish-cache.secretConfig" . }}
{{- if not (eq $secretConfig "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "varnish-cache.fullname" . }}-secret
  labels:
    {{- include "varnish-cache.labels" . | nindent 4 }}
data:
  secret: {{ $secretConfig | trim | b64enc }}
{{- end }}
